
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KSL_HMS.DB
{

using System;
    using System.Collections.Generic;
    
public partial class BillDetail
{

    public int numBillDetailID { get; set; }

    public Nullable<int> numBillHeaderID { get; set; }

    public Nullable<int> numChargeTypeID { get; set; }

    public Nullable<int> numRoomID { get; set; }

    public Nullable<int> numLocationID { get; set; }

    public Nullable<int> numItemID { get; set; }

    public Nullable<int> numBookingDetailID { get; set; }

    public Nullable<decimal> numCost { get; set; }

    public Nullable<decimal> numQuantity { get; set; }

    public Nullable<bool> bitDiscountOffered { get; set; }

    public Nullable<decimal> numDiscount { get; set; }

    public Nullable<decimal> numFinalCost { get; set; }

    public Nullable<bool> bitActive { get; set; }

    public Nullable<int> numCreatedByID { get; set; }

    public Nullable<System.DateTime> dtCreatedDate { get; set; }

    public Nullable<int> numUpdatetdByID { get; set; }

    public Nullable<System.DateTime> dtUpdatetDate { get; set; }

    public Nullable<int> numDeletedByID { get; set; }

    public Nullable<System.DateTime> dtDeletedDate { get; set; }

    public Nullable<decimal> numDuration { get; set; }

    public Nullable<int> numKiteRentalDetailID { get; set; }

    public Nullable<int> numKiteTrainingDetailID { get; set; }



    public virtual ChargeType ChargeType { get; set; }

    public virtual Item Item { get; set; }

    public virtual Location Location { get; set; }

    public virtual BillHeader BillHeader { get; set; }

    public virtual BookingDetail BookingDetail { get; set; }

    public virtual Room Room { get; set; }

    public virtual KiteRentalDetail KiteRentalDetail { get; set; }

    public virtual KiteTrainingDetail KiteTrainingDetail { get; set; }

}

}
