//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSL_HMS.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookingHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingHeader()
        {
            this.BillHeaders = new HashSet<BillHeader>();
            this.BookingDetails = new HashSet<BookingDetail>();
            this.Receipts = new HashSet<Receipt>();
        }

        public int numBookingHeaderID { get; set; }
        public string varBookingStartToEndDates { get; set; }
        public Nullable<System.DateTime> dtFromDate { get; set; }
        public Nullable<System.DateTime> dtToDate { get; set; }
        public Nullable<int> numRoomTypeID { get; set; }
        public Nullable<int> numRoomID { get; set; }
        public Nullable<bool> bitStandardRate { get; set; }
        public Nullable<decimal> numRate { get; set; }
        public Nullable<bool> bitTransportRequired { get; set; }
        [DataType(DataType.MultilineText)]
        [MaxLength(500, ErrorMessage = "500 Characters Allowed For Flight Details.")]
        public string varFlightDetails { get; set; }
        public Nullable<System.DateTime> dtCheckInDateTime { get; set; }
        public Nullable<System.DateTime> dtCheckOutDateTime { get; set; }
        [DataType(DataType.MultilineText)]
        [MaxLength(500, ErrorMessage = "500 Characters Allowed For Remarks.")]
        public string varRemarks { get; set; }
        public Nullable<bool> bitKSLessonRequired { get; set; }
        public string varKsLessonRequiredStartToEndDates { get; set; }
        public Nullable<System.DateTime> dtKsLessonRequiredFrom { get; set; }
        public Nullable<System.DateTime> dtKsLessonRequiredTo { get; set; }
        public Nullable<bool> bitKSRentalRequired { get; set; }
        public string varKSRentalRequiredStartToEndDates { get; set; }
        public Nullable<System.DateTime> dtKSRentalRequiredFrom { get; set; }
        public Nullable<System.DateTime> dtKSRentalRequiredTo { get; set; }
        public Nullable<bool> bitActive { get; set; }
        public Nullable<bool> bitCheckedIn { get; set; }
        public Nullable<bool> bitCheckedOut { get; set; }
        public Nullable<int> numCreatedByID { get; set; }
        public Nullable<System.DateTime> dtCreatedDate { get; set; }
        public Nullable<int> numUpdatetdByID { get; set; }
        public Nullable<System.DateTime> dtUpdatetDate { get; set; }
        public Nullable<int> numDeletedByID { get; set; }
        public Nullable<System.DateTime> dtDeletedDate { get; set; }
        public Nullable<int> numBookingRefferenceID { get; set; }
        public int numGuestID { get; set; }
        public string varGuestName { get; set; }
        [EmailAddress]
        [Display(Name = "Email")]
        public string varGuestEmail { get; set; }
        public string varGuestPPNo { get; set; }
        public Nullable<int> numGuestChargeTypeID { get; set; }
        public Nullable<int> numAdultsCount { get; set; }
        public Nullable<int> numChildrensCount { get; set; }
        public Nullable<int> numInfantsCount { get; set; }
        public string varBookingPersonName { get; set; }
        [EmailAddress]
        [Display(Name = "Email")]
        public string varBookingPersonEmail { get; set; }
        public Nullable<bool> bitAgentRequired { get; set; }
        public string varAgentName { get; set; }

        public virtual RoomType RoomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillHeader> BillHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual BookingRefference BookingRefference { get; set; }
        public virtual Room Room { get; set; }
    }
}
