
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KSL_HMS.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Item
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Item()
    {

        this.BillDetails = new HashSet<BillDetail>();

        this.KiteTrainingRates = new HashSet<KiteTrainingRate>();

        this.KiteRentalRates = new HashSet<KiteRentalRate>();

        this.KiteRentalHeaders = new HashSet<KiteRentalHeader>();

        this.KiteTrainingHeaders = new HashSet<KiteTrainingHeader>();

    }


    public int numItemID { get; set; }

    public string varItemName { get; set; }

    public string varItemDescription { get; set; }

    public Nullable<int> numItemTypeID { get; set; }

    public Nullable<decimal> numRatePerUnit { get; set; }

    public Nullable<bool> bitActive { get; set; }

    public Nullable<int> numCreatedByID { get; set; }

    public Nullable<System.DateTime> dtCreatedDate { get; set; }

    public Nullable<int> numUpdatetdByID { get; set; }

    public Nullable<System.DateTime> dtUpdatetDate { get; set; }

    public Nullable<int> numDeletedByID { get; set; }

    public Nullable<System.DateTime> dtDeletedDate { get; set; }

    public Nullable<bool> bitIsDeleted { get; set; }

    public Nullable<int> numItemOrder { get; set; }



    public virtual ItemType ItemType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BillDetail> BillDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<KiteTrainingRate> KiteTrainingRates { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<KiteRentalRate> KiteRentalRates { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<KiteRentalHeader> KiteRentalHeaders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<KiteTrainingHeader> KiteTrainingHeaders { get; set; }

}

}
