//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSL_HMS.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KiteTrainingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KiteTrainingDetail()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }

        public int numKiteTrainingDetailID { get; set; }
        public Nullable<int> numKiteTrainingHeaderID { get; set; }
        public Nullable<int> numBookingHeaderID { get; set; }
        [Required(ErrorMessage = "Please Select Guest.")]
        public Nullable<int> numBookingDetailID { get; set; }
        [Required(ErrorMessage = "Please Select Item.")]
        public Nullable<int> numItemID { get; set; }
        [Required(ErrorMessage = "Please Select Instructor.")]
        public Nullable<int> numInstructorID { get; set; }
        [Required(ErrorMessage = "Please Select Training Date.")]
        public Nullable<System.DateTime> dtKiteTrainingDate { get; set; }
        [Required(ErrorMessage = "Please Enter No Of People.")]
        public Nullable<int> numTrainingPaxCount { get; set; }
        [Required(ErrorMessage = "Please Enter Training Hours.")]
        [Range(0.01, 1000000000000000, ErrorMessage = "Please Enter Valid Hours.")]
        public Nullable<decimal> numKiteTrainingHours { get; set; }
        public Nullable<decimal> numKiteTrainingRate { get; set; }
        public Nullable<decimal> numKiteTrainingCost { get; set; }
        public Nullable<bool> bitActive { get; set; }
        public Nullable<int> numCreatedByID { get; set; }
        public Nullable<System.DateTime> dtCreatedDate { get; set; }
        public Nullable<int> numUpdatetdByID { get; set; }
        public Nullable<System.DateTime> dtUpdatetDate { get; set; }
        public Nullable<int> numDeletedByID { get; set; }
        public Nullable<System.DateTime> dtDeletedDate { get; set; }

        public virtual Instructor Instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual BookingDetail BookingDetail { get; set; }
        public virtual KiteTrainingHeader KiteTrainingHeader { get; set; }
    }
}
