//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSL_HMS.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KiteRentalDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KiteRentalDetail()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }

        public int numKiteRentalDetailID { get; set; }
        public Nullable<int> numKiteRentalHeaderID { get; set; }
        public Nullable<int> numBookingHeaderID { get; set; }
        [Required(ErrorMessage = "Please Select Guest.")]
        public Nullable<int> numBookingDetailID { get; set; }
        [Required(ErrorMessage = "Please Select Item.")]
        public Nullable<int> numItemID { get; set; }
        [Required(ErrorMessage = "Please Select Renting Date.")]
        public Nullable<System.DateTime> dtKiteRentalDate { get; set; }
        [Required(ErrorMessage = "Please Enter Renting Quantity.")]
        [Range(0.01, 1000000000000000, ErrorMessage = "Please Enter Valid Quantity.")]
        public Nullable<decimal> numKiteRentalQuantity { get; set; }
        [Required(ErrorMessage = "Please Enter Renting Days.")]
        [Range(0.01, 1000000000000000, ErrorMessage = "Please Enter Valid Days.")]
        public Nullable<decimal> numKiteRentalDays { get; set; }
        public Nullable<decimal> numKiteRentalRate { get; set; }
        public Nullable<decimal> numKiteRentalCost { get; set; }
        public Nullable<bool> bitActive { get; set; }
        public Nullable<int> numCreatedByID { get; set; }
        public Nullable<System.DateTime> dtCreatedDate { get; set; }
        public Nullable<int> numUpdatetdByID { get; set; }
        public Nullable<System.DateTime> dtUpdatetDate { get; set; }
        public Nullable<int> numDeletedByID { get; set; }
        public Nullable<System.DateTime> dtDeletedDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual BookingDetail BookingDetail { get; set; }
        public virtual KiteRentalHeader KiteRentalHeader { get; set; }
    }
}
