
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KSL_HMS.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Receipt
{

    public int numReceiptID { get; set; }

    public string varReceiptNo { get; set; }

    public Nullable<int> numBookingHeaderID { get; set; }

    public Nullable<int> numBillHeaderID { get; set; }

    public Nullable<int> numPaymentTypeID { get; set; }

    public Nullable<int> numReciptTypeID { get; set; }

    public Nullable<decimal> numAmount { get; set; }

    public Nullable<bool> bitActive { get; set; }

    public Nullable<int> numCreatedByID { get; set; }

    public Nullable<System.DateTime> dtCreatedDate { get; set; }

    public Nullable<int> numUpdatetdByID { get; set; }

    public Nullable<System.DateTime> dtUpdatetDate { get; set; }

    public Nullable<int> numDeletedByID { get; set; }

    public Nullable<System.DateTime> dtDeletedDate { get; set; }

    public Nullable<int> numBookingRefferenceID { get; set; }

    public Nullable<bool> bitSingleBooking { get; set; }

    public Nullable<int> numCurrencyID { get; set; }

    public Nullable<bool> bitIsDefaultCurrency { get; set; }

    public Nullable<decimal> numCurrencyRate { get; set; }

    public Nullable<decimal> numPayInCurrencyAmount { get; set; }



    public virtual PaymentType PaymentType { get; set; }

    public virtual ReciptType ReciptType { get; set; }

    public virtual BillHeader BillHeader { get; set; }

    public virtual BookingHeader BookingHeader { get; set; }

    public virtual Currency Currency { get; set; }

    public virtual BookingRefference BookingRefference { get; set; }

}

}
