
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KSL_HMS.DB
{

using System;
    using System.Collections.Generic;
    
public partial class ReciptType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ReciptType()
    {

        this.Receipts = new HashSet<Receipt>();

    }


    public int numReciptTypeID { get; set; }

    public string varReciptTypeName { get; set; }

    public string varReciptTypeDescription { get; set; }

    public Nullable<bool> bitActive { get; set; }

    public Nullable<int> numCreatedByID { get; set; }

    public Nullable<System.DateTime> dtCreatedDate { get; set; }

    public Nullable<int> numUpdatetdByID { get; set; }

    public Nullable<System.DateTime> dtUpdatetDate { get; set; }

    public Nullable<int> numDeletedByID { get; set; }

    public Nullable<System.DateTime> dtDeletedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Receipt> Receipts { get; set; }

}

}
