
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KSL_HMS.DB
{

using System;
    using System.Collections.Generic;
    
public partial class RoomTypeRate
{

    public int numRoomTypeRateID { get; set; }

    public Nullable<int> numRoomTypeID { get; set; }

    public Nullable<decimal> numRatePerPerson { get; set; }

    public Nullable<bool> bitActive { get; set; }

    public Nullable<int> numCreatedByID { get; set; }

    public Nullable<System.DateTime> dtCreatedDate { get; set; }

    public Nullable<int> numUpdatetdByID { get; set; }

    public Nullable<System.DateTime> dtUpdatetDate { get; set; }

    public Nullable<int> numDeletedByID { get; set; }

    public Nullable<System.DateTime> dtDeletedDate { get; set; }

    public Nullable<int> numPersonCount { get; set; }



    public virtual RoomType RoomType { get; set; }

}

}
