//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSL_HMS.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class RoomType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomType()
        {
            this.BookingHeaders = new HashSet<BookingHeader>();
            this.RoomTypeRates = new HashSet<RoomTypeRate>();
            this.Rooms = new HashSet<Room>();
        }

        public int numRoomTypeID { get; set; }
        [MaxLength(50, ErrorMessage = "50 Characters Allowed For Room Category Name.")]
        [Remote("IsAlreadyExists", "RoomTypes", HttpMethod = "POST", ErrorMessage = "Room Category Name Already Available.")]
        [Required(ErrorMessage = "Please Enter Room Category Name.")]
        public string varRoomTypeName { get; set; }
        [DataType(DataType.MultilineText)]
        [MaxLength(500, ErrorMessage = "500 Characters Allowed For Room Category Description.")]
        [Required(ErrorMessage = "Please Enter Room Category Description.")]
        public string varRoomTypeDescription { get; set; }
        public Nullable<bool> bitActive { get; set; }
        public Nullable<int> numCreatedByID { get; set; }
        public Nullable<System.DateTime> dtCreatedDate { get; set; }
        public Nullable<int> numUpdatetdByID { get; set; }
        public Nullable<System.DateTime> dtUpdatetDate { get; set; }
        public Nullable<int> numDeletedByID { get; set; }
        public Nullable<System.DateTime> dtDeletedDate { get; set; }
        public HttpPostedFileBase RoomCategoryImage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingHeader> BookingHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomTypeRate> RoomTypeRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
