
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KSL_HMS.DB
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public int numUserID { get; set; }

    public string varFirstName { get; set; }

    public string varLastName { get; set; }

    public string varUserName { get; set; }

    public string varPassword { get; set; }

    public string varNIC { get; set; }

    public string varEPF { get; set; }

    public string varEmail { get; set; }

    public Nullable<int> numPermissionID { get; set; }

    public Nullable<bool> bitActive { get; set; }

    public Nullable<System.DateTime> dtCreatedDate { get; set; }

    public Nullable<int> numUpdatetdByID { get; set; }

    public Nullable<System.DateTime> dtUpdatetDate { get; set; }

    public Nullable<int> numDeletedByID { get; set; }

    public Nullable<System.DateTime> dtDeletedDate { get; set; }



    public virtual Permission Permission { get; set; }

}

}
